/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -fcase-insensitive-filenames -gen-OER -gen-JER -fincludes-quoted -fwide-types -pdu=all -S ./skeletons -D ./generated-files/2024`
 */

#include "Ieee1609Dot2BaseTypes_Psid.h"

int
Ieee1609Dot2BaseTypes_Psid_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* asn1c emits a self-referential general constraint for (0..MAX). */
	return 0;
}

/*
 * This type is implemented using INTEGER,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Ieee1609Dot2BaseTypes_Psid_constr_1 CC_NOTUSED = {
	{ 0, 1 }	/* (0..MAX) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Ieee1609Dot2BaseTypes_Psid_constr_1 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2BaseTypes_Psid = {
	"Psid",
	"Psid",
	&asn_OP_INTEGER,
	asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1,
	sizeof(asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1)
		/sizeof(asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1[0]), /* 1 */
	asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1)
		/sizeof(asn_DEF_Ieee1609Dot2BaseTypes_Psid_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Ieee1609Dot2BaseTypes_Psid_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Ieee1609Dot2BaseTypes_Psid_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		Ieee1609Dot2BaseTypes_Psid_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

